version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pantry_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - auth
    restart: always

  auth:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pantry_auth
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always