name: PantryChef CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.6
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 . --exclude=venv,__pycache__

    - name: Build Docker images
      run: |
        docker build -t pantry-auth -f backend/Dockerfile .
        docker build -t pantry-frontend -f Dockerfile .