name: PantryChef CI/CD Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    env:
      GHCR_USER: ${{ github.repository_owner }}
     
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push pantry-auth image
      run: |
          loweruser=$(echo "${GHCR_USER}" | tr '[:upper:]' '[:lower:]')
          docker buildx build --push \
            -f ./backend/Dockerfile \
            -t ghcr.io/${loweruser}/pantry-auth:latest \
            -t ghcr.io/${loweruser}/pantry-auth:${{ github.sha }} \
            ./backend

    - name: Build and push pantry-frontend image
      run: |
          loweruser=$(echo "${GHCR_USER}" | tr '[:upper:]' '[:lower:]')
          docker buildx build --push \
            -f ./Dockerfile \
            -t ghcr.io/${loweruser}/pantry-frontend:latest \
            -t ghcr.io/${loweruser}/pantry-frontend:${{ github.sha }} \
            .